name: core_project
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

#Version flutter 3.7.1
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  #================
  ##FUNDAMENTAL

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #Database
  sqflite: ^2.2.4+1
  #HTTPs Requests
  dio: ^4.0.6
  #State management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  #Singleton Package
  get_it: ^7.2.0
  get_it_mixin: ^3.1.4+2
  #Cache management
  shared_preferences: ^2.0.17
  #Get directory of project
  path_provider: ^2.0.12
  path_provider_foundation: ^2.1.1
  #Add multiple responses from a function
  dartz: ^0.10.1
  #Cryptografh
  crypto: ^3.0.2
  #Router Options
  go_router: ^6.0.2
  #Check connectivity
  internet_connection_checker_plus: ^1.0.1
  #Utilities
  intl: ^0.17.0
  #================

  #================
  ##EXTRAS

  #More theme options
  flex_color_scheme: ^6.1.2
  #Gap between widgets
  gap: ^2.0.1
  #More Animation loading options
  loading_animation_widget: ^1.2.0+4
  #Simplify media queries gets 
  sized_context: ^1.0.0+1
  #extras funcionality to Columns and Rows
  flextras: ^1.0.0
  #Add svg support
  flutter_svg: ^1.1.6
  #Skeleton effect with waves
  shimmer: ^2.0.0
  #video player
  youtube_player_flutter: ^8.1.2
  #Add more Widgets from Aligments like "Center" widget
  extra_alignments: ^1.0.0+1
  #Add email validation
  email_validator: ^2.1.17
  #Show toasts
  fluttertoast: ^8.1.2
  #Simplify to make RichTexts
  simple_rich_text: ^2.0.49
  flutter_animate: ^3.1.0
  page_transition: ^2.0.9
  #================

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Myriad Pro
      fonts:
        - asset: assets/fonts/Myriad-Pro-Light.otf
          weight: 300
        - asset: assets/fonts/Myriad-Pro-Regular.ttf
          weight: 400
        - asset: assets/fonts/Myriad-Pro-Bold.ttf
          weight: 700
        - asset: assets/fonts/Myriad-Pro-Black.otf
          weight: 900
